# coding: utf-8
from __future__ import absolute_import

#/
## 1 and 2 are used by |argparse|.
MAIN_RET_V_KBINT_OK = 0
MAIN_RET_V_EXC_LEAK_ER = 3
MAIN_RET_V_VER_SHOW_OK = 0
MAIN_RET_V_PSR_TPLT_FILE_READ_ER = 4
MAIN_RET_V_EXT_OPTS_LOAD_ER = 5
MAIN_RET_V_RULES_FILE_READ_ER = 6
MAIN_RET_V_RULES_OBJ_LOAD_ER = 7
MAIN_RET_V_RULES_OBJ_NOT_STR_ER = 8
MAIN_RET_V_RULES_PARSE_ER = 9
MAIN_RET_V_SRC_FILE_READ_ER = 10
MAIN_RET_V_SRC_OBJ_LOAD_ER = 11
MAIN_RET_V_SRC_OBJ_NOT_STR_ER = 12
MAIN_RET_V_PSR_CODE_WRITE_STDOUT_OK = 0
MAIN_RET_V_PSR_CODE_WRITE_FILE_ER = 13
MAIN_RET_V_PSR_CODE_WRITE_FILE_OK = 0
MAIN_RET_V_PSR_CODE_LOAD_ER = 14
MAIN_RET_V_PSR_CODE_CALL_ER = 15
MAIN_RET_V_PSR_CODE_CALL_OK = 0

#/
PSR_CODE_DYN_MOD_NAME = 'aoiktopdownparser.psr_code_dyn_mod'
